name: vpsrun
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start tmate session (multi-ssh)
        uses: mxschmitt/action-tmate@v3
