name: vpsrun
on:
  workflow_dispatch:

jobs:
  ssh-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH server & ngrok
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo 'root:rootpassword' | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart

          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y

      - name: Start ngrok tunnel
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok tcp 22 > ngrok.log &
          sleep 5
          NGROK_URL=$(curl -s localhost:4040/api/tunnels | grep -o 'tcp://[^"]*')
          echo "🟢 SSH ready: $NGROK_URL"
          echo "ssh root@$(echo $NGROK_URL | cut -d/ -f3 | sed 's/:/ -p /')"
          tail -f /dev/null
